name: deploy-azure

on:
  push:
    branches: ['latest']
  workflow_dispatch:

jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      -
        name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: deploy:test 240100-tt-mail
          workdir: jobs/deploy
          install_only: false
